### PR TITLE
Bump Zeebe version for release 8.1.6

### PR DESCRIPTION
**Pull request by Zelldon**
Update example zeebe patch versions to 8.1.6

### CODE REVIEW

**Comment by Zelldon** [comment]
@menski @npepinpe not sure why it getting a different hash for go client :thinking: Any idea? Can it be that I had to retry the release? :thinking:

**Comment by npepinpe** [comment]
not sure, that's interesting :thinking: did we recreate the tag?

**Comment by Zelldon** [comment]
I delete the tag and a new one was created. I had hoped this should be it.

**Comment by Zelldon** [comment]
I think this is something with my local cache, since dependabot was able to create a working PR here https://github.com/zeebe-io/zeebe-chaos/pull/303/files

**Comment by Zelldon** [comment]
Ok this was hard. I emptied the go cache several times `go clean -modcache` and reverted the commits, renamed the zeebe repo etc.

But then I had an interesting find:

I installed go1.17 https://go.dev/doc/manage-install

```
$ go install golang.org/dl/go1.17.7@latest
$ go1.17.7 download
```

* Reverted the last commit.
* Run go get again: `go1.17.7 get -x -u -v github.com/camunda/zeebe/clients/go/v8@v8.1.6` failed with hash mismatch. 
* I emptied the cache again: `go clean -modcache`
* Run again `go1.17.7 get...` -> Success. :white_check_mark: 

it looks like the problem is when using newer version go :/

**Review by npepinpe — APPROVED** [review]
:+1: 

Good catch! I'm not 100% sure why new versions (and not new major versions!) would compute a different hash :thinking: Perhaps it fetches different versions/artifacts based on the version? I'm not familiar enough with how it resolves things :shrug:

**Pull request merged**
