### PR TITLE
Removed docker-compose file that is now on camunda-platform repo

### PR DESCRIPTION
**Pull request by berndruecker**
I would like to remove this docker-compose file as it is now in a different place

### CODE REVIEW

**Comment by berndruecker** [comment]
Related to https://github.com/camunda-cloud/camunda-cloud-documentation/issues/812

**Comment by menski** [comment]
As far as I'm aware this is still linked from camunda.com, I'm waiting for confirmation that this is updated before accepting this change.

**Review by menski — APPROVED** [review]
The link on camunda.com was adjusted so we can merge this

**Comment by berndruecker** [comment]
Great - thx!

**Pull request merged**
